ems.web/Controllers/CompanyController.cs
using ems.core;
using ems.domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ems.web.Controllers
{
    public class CompanyController : Controller
    {
        CompanyRepository Repo = new CompanyRepository();
        // GET: Company
        public ActionResult Edit()
        {
            Company model = Repo.GetCompanyDetails();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Company model)
        {
            if(ModelState.IsValid)
            {
                int i = Repo.Edit(model);
                if(i>0)
                {
                    TempData["message"] = "Successfully Updated";
                }
            }
            else
            {
                return View(model);
            }
            return RedirectToAction("Edit");
        }
    }
}

ems.web/Controllers/CustomerController.cs
using ems.core;
using ems.domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ems.web.Controllers
{
    public class CustomerController : BaseController
    {
        CustomerRepository repo = new CustomerRepository();
        public ActionResult Index()
        {
            List<Customer> model = repo.GetCustomerList();
            TempData["ExportData"] = model;
            ViewBag.datasource = model;
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Customer model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Create(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Saved";
                    return RedirectToAction("Create");
                }
                else
                {
                    return View(model);
                }
            }
            return View(model);
        }
        public ActionResult Edit(int? Id)
        {
            Customer model = repo.GetCustomer(Id ?? 0);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Customer model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Edit(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Updated";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

ems.web/Controllers/GSTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ems.domain;
using ems.core;
using Syncfusion.EJ.Export;
using Syncfusion.JavaScript.Models;
using Syncfusion.XlsIO;

namespace ems.web.Controllers
{
    public class GSTController : BaseController
    {
        // GET: GST
        GSTRepository repo = new GSTRepository();
        public ActionResult Index()
        {
            List<GST> model = repo.GetGSTList();
            TempData["ExportData"] = model;
            ViewBag.datasource = model;
            return View();
        }
        public ActionResult Create()
        {
            GST model = new GST();
            return View(model);
        }
        public ActionResult Edit(int? Id)
        {
            GST model = repo.GetGSTRate(Id ?? 0);
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(GST model)
        {
            if(ModelState.IsValid)
            {
                int rowsAffected = repo.Create(model);
                if(rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Saved";
                    return RedirectToAction("Create");
                }
                else
                {
                    return View(model);
                }
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(GST model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Edit(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Updated";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

ems.web/Controllers/VendorController.cs
using ems.core;
using ems.domain;
using Syncfusion.JavaScript.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ems.web.Controllers
{
    public class VendorController : Controller
    {
        VendorRepository repo = new VendorRepository();
        public ActionResult Index()
        {
            List<Vendor> model = repo.GetVendorList();
            TempData["ExportData"] = model;
            ViewBag.datasource = model;
            return View();
        }
        public ActionResult Create()
        {
            fillDropdowns();
            return View();
        }
        [HttpPost]
        public ActionResult Create(Vendor model)
        {
            if(ModelState.IsValid)
            {
                int row = repo.Create(model);
                if(row>0)
                {
                    TempData["message"] = "Successfully Created";
                }
            }
            else
            {
                fillDropdowns();
                return View(model);
            }
            return RedirectToAction("Create");
        }
        public ActionResult Edit(int? Id)
        {
            Vendor model = repo.GetVendorDetails(Id ?? 0);
            fillDropdowns();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Vendor model)
        {
            if (ModelState.IsValid)
            {
                int row = repo.Edit(model);
                if (row > 0)
                {
                    TempData["message"] = "Successfully Updated";
                }
            }
            else
            {
                fillDropdowns();
                return View(model);
            }
            return RedirectToAction("Index");
        }
        private void fillDropdowns()
        {
            DropDownListProperties DropdownProperties = new DropDownListProperties();
            DropdownProperties.DataSource = repo.GetVendorTypeList();
            DropdownProperties.Width = "100%";
            DropDownListFields DropdownFields = new DropDownListFields();
            DropdownFields.Text = "VendorTypeName";
            DropdownFields.Id = "VendorTypeId";
            DropdownFields.Value = "VendorTypeId";
            DropdownProperties.DropDownListFields = DropdownFields;
            ViewData["VendorTypeDropdownModel"] = DropdownProperties;
        }
    }
}

ems.web/Views/Shared/_ControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">
    @* BEGIN Tabs *@
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    @* END Tabs *@
    <div class="tab-content">
        @* BEGIN Home Tab *@
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        @* END Home Tab *@
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        @* BEGIN Settings Tab *@
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
            </form>
        </div>
        @* END Settings Tab *@
    </div>
</aside>
@* Add the sidebar's background. This div must be placed immediately after the control sidebar *@
<div class="control-sidebar-bg"></div>

ems.web/Views/Shared/_Header.cshtml
<header class="main-header">
    @* BEGIN Logo *@
    <a href="@Url.Action("Index", "Home")" class="logo">
        @* Mini logo for sidebar 50x50 pixels *@
        <span class="logo-mini"><b>SK</b></span>
        @* Logo for regular state and mobile devices *@
        <span class="logo-lg"><b>SK-</b>ERP</span>
    </a>
    @* END Logo *@
    @* BEGIN Header *@
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @* BEGIN Messages *@
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/Content/img/user.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>
                @* END Messages *@
                @* BEGIN Notifications *@
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                @* END Notifications *@
                @* BEGIN Tasks *@
                <li class="dropdown tasks-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <div class="progress xs">
                                            @* Change the css width attribute to simulate progress *@
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>
                @* END Tasks *@
                @* BEGIN User Account Menu *@
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="~/Content/img/user.jpg" class="user-image" alt="User Image">
                        <span class="hidden-xs">Sreekanth A</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="~/Content/img/user.jpg" class="img-circle" alt="User Image">

                            <p>
                                Sreekanth A - Administrator
                                <small>Member since Nov. 2009</small>
                            </p>
                        </li>
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                @* END User Account Menu *@
                @* BEGIN Control Sidebar Toggle Button *@
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
                @* END Control Sidebar Toggle Button *@
            </ul>
        </div>
    </nav>
</header>

ems.web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using WebHelpers.Mvc5.Enum
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        SK-ERP
    </title>    
    @Styles.Render("~/Content/ej/web/bootstrap-theme/ej.web.all.min.css")
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @Styles.Render("~/Bundles/css")
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @Html.Partial("_Header")
        @Html.Partial("_Sidebar")
        <div class="content-wrapper">
            @*<section class="content-header">
                <h1>
                    <small>@ViewBag.Description</small>
                </h1>
            </section>*@
            <section class="content">                
                @RenderBody()
            </section>
        </div>

        @Html.Partial("_ControlSidebar")
    </div>

    <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
    <script src="@EnumHandler.HandlerUrl"></script>
    @Scripts.Render("~/Bundles/js")
    @RenderSection("ViewSpecificJavascript", required: false)
    @Scripts.Render("~/Scripts/jsrender.min.js")
    @Scripts.Render("~/Scripts/ej/web/ej.web.all.min.js")
    @RenderSection("scripts", required: false)    
    @Html.EJ().ScriptManager();
</body>
</html>

ems.web/Views/Shared/_Sidebar.cshtml
@using WebHelpers.Mvc5
<aside class="main-sidebar">
    <section class="sidebar">
        @* BEGIN Search *@
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        @* END Search *@
        @* BEGIN Menu *@
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">HEADER</li>
            <li class="@Url.IsLinkActive("Index", "Home")">
                <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> <span>Home</span></a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-cogs"></i> <span>General Masters</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Create","Customer")"><i class="fa fa-dollar"></i> <span>Customer</span></a></li>
                    <li><a href="@Url.Action("Create","Vendor")"><i class="fa fa-user-secret"></i> <span>Vendor</span></a></li>
                    <li><a href="@Url.Action("Create","GST")"><i class="fa fa-ship"></i> <span>GST Rates</span></a></li>
                    <li><a href="@Url.Action("Create","Warehouse")"><i class="fa fa-ship"></i> <span>Warehouse</span></a></li>                    
                    <li><a href="#"><i class="fa fa-ship"></i> <span>Fiscal Year</span></a></li>
                    <li><a href="@Url.Action("Edit","Company")"><i class="fa fa-ship"></i> <span>Company Details</span></a></li>                    
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-industry"></i> <span>Purchase</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Purchase Indent</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Supplier Order</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>GRN</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Q.A</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Purchase Bill</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-industry"></i> <span>Sales</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Create","ProductMainGroup")"><i class="fa fa-tags"></i> <span>Product Main Group</span></a></li>
                    <li><a href="@Url.Action("Create","ProductSubGroup")"><i class="fa fa-tags"></i> <span>Product Sub Group</span></a></li>
                    <li><a href="#"><i class="fa fa-tags"></i> <span>Product Defenition</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Quotation</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>GIN</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Sales Invoice</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Stock Reconciliation</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-industry"></i> <span>Service</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Create","ServiceExpense")"><i class="fa fa-tags"></i> <span>Service/Expense Defenition</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Quotation</span></a></li>
                    <li><a href="@Url.Action("Create","ServiceInvoice")"><i class="fa fa-cube"></i> <span>Service Invoice</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Service Bill</span></a></li>                    
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-industry"></i> <span>Accounts</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-ship"></i> <span>Chart of Accounts</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Expense Bill</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Account Payables</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Account Receivables</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Payment to Vendors</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Receipt from Customer</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Bank/Cash Payment</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Bank/Cash Receipt</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Fund Transfer</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Debit Note</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Credit Note</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Journal Entry</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Bank Reconciliaton</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-hourglass-end"></i> <span>H.R</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-random"></i> <span>Department</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Designation</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Wage Grade</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Salary Period</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Employee</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Leaves</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Attendance Sheet</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-hourglass-end"></i> <span>Reports</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-random"></i> <span>Stock Reports</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>GSTR-1</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>GSTR-2</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Purchase Reports</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Sales Reports</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Service Reports</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Trial Balance</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Balance Sheet</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Profit & Loss</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Trading  P&L</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Bank/Cash Status</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Ledger Detailed Report</span></a></li>
                </ul>
            </li>
        </ul>
        @* END Menu *@
    </section>
</aside>