ems.web/Controllers/WarehouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ems.domain;
using ems.core;
using Syncfusion.EJ.Export;
using Syncfusion.JavaScript.Models;
using Syncfusion.XlsIO;

namespace ems.web.Controllers
{
    public class WarehouseController : BaseController
    {
        WarehouseRepository repo = new WarehouseRepository();       
        public ActionResult Index()
        {
            List<Warehouse> model = repo.GetWarehouseList();
            TempData["ExportData"] = model;
            ViewBag.datasource = model;
            return View();
        }
        public ActionResult Create()
        {
            Warehouse model = new Warehouse();
            return View(model);
        }
        public ActionResult Edit(int? Id)
        {
            Warehouse model = repo.GetWarehouse(Id ?? 0);
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(Warehouse model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Create(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Saved";
                    return RedirectToAction("Create");
                }
                else
                {
                    return View(model);
                }
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Warehouse model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Edit(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Updated";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

ems.web/Views/Warehouse/Create.cshtml
@model ems.domain.Warehouse
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function GotoPreviosList()
    {
        location.href = '@Url.Action("Index", "Warehouse")';
    }
</script>
<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Warehouse</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.Partial("_form",Model)
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-default">Cancel</button>
                    <button type="button" class="btn btn-default" onclick="GotoPreviosList()">Previous</button>
                    <button type="submit" class="btn btn-info pull-right">Save</button>
                </div>
            }
            
        </div>
        <!-- /.box -->
    </div>
</div>

ems.web/Views/Warehouse/Edit.cshtml
@model ems.domain.Warehouse
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function GotoPreviosList()
    {
        location.href = '@Url.Action("Index", "Warehouse")';
    }
</script>
<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">GST Rates</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(model=>model.whId)
                @Html.Partial("_form", Model)
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-default">Cancel</button>
                    <button type="button" class="btn btn-default" onclick="GotoPreviosList()">Previous</button>
                    <button type="submit" class="btn btn-info pull-right">Update</button>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>
</div>

ems.web/Views/Warehouse/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@(Html.EJ().Grid<ems.domain.Warehouse>("Grid")
                 .Datasource((IEnumerable<ems.domain.Warehouse>)ViewBag.datasource)
                 .ToolbarSettings(toolBar => toolBar.ShowToolbar().ToolbarItems(items =>
                 {
                     items.AddTool(ToolBarItems.ExcelExport);
                     items.AddTool(ToolBarItems.WordExport);
                     items.AddTool(ToolBarItems.PdfExport);
                 }))
                 .AllowPaging()
                 .IsResponsive(true)
                .EnableResponsiveRow(true)
                .AllowFiltering()
                 .Columns(col =>
                 {
                     col.Field("whId").Visible(true).HeaderText("whId").IsIdentity(true).IsPrimaryKey(true).TextAlign(TextAlign.Left).Add();
                     col.Field(p => p.whCode).HeaderText("Code").TextAlign(TextAlign.Left).Width("10%").Add();
                     col.Field(p => p.whName).HeaderText("Warehouse").TextAlign(TextAlign.Left).Width("30%").Add();
                     col.Field(p => p.whTel).HeaderText("Telephone").TextAlign(TextAlign.Left).Width("20%").Add();
                     col.Field(p => p.whMob).HeaderText("Mobile").TextAlign(TextAlign.Left).Width("20%").Add();
                     col.Field(p => p.whContactPerson).HeaderText("Contact Person").TextAlign(TextAlign.Left).Width("20%").Add();
                 })
                 .ClientSideEvents(events=>events.RecordDoubleClick("DoubleClicked"))
                 .Mappers(map => map.ExportToExcelAction("Base/ExportToExcel").ExportToWordAction("Base/ExportToWord").ExportToPdfAction("Base/ExportToPdf"))
)

<script>
    function DoubleClicked(args)
    {
        var grid = $("#Grid").ejGrid("instance");
        var id = args.data[grid.getPrimaryKeyFieldNames()[0]];
        var url = '@Url.Action("Edit", "Warehouse")';
        location.href = url + "/" + id;
    }
</script>

ems.web/Views/Warehouse/_form.cshtml
@model ems.domain.Warehouse
<div class="box-body">
    <div class="form-group">
        @Html.LabelFor(m => m.whCode)
        <div class="row">
            <div class="col-xs-3">
                @Html.TextBoxFor(model => model.whCode, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.whCode)
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.whName)
        <div class="row">
            <div class="col-xs-3">
                @Html.TextBoxFor(model => model.whName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.whName)
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.whAddress)
        @Html.TextAreaFor(model => model.whAddress, new { @class = "form-control", @rows = "3" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.whTel)
        <div class="row">
            <div class="col-xs-3">
                @Html.TextBoxFor(model => model.whTel, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.whTel)
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.whMob)
        <div class="row">
            <div class="col-xs-3">
                @Html.TextBoxFor(model => model.whMob, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.whMob)
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.whContactPerson)
        <div class="row">
            <div class="col-xs-3">
                @Html.TextBoxFor(model => model.whContactPerson, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.whContactPerson)
            </div>
        </div>
    </div>    
</div>