prms.web/Controllers/ProductMainGroupController.cs
using ems.core;
using ems.domain;
using ems.domain.ViewModels;
using Syncfusion.JavaScript.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prms.web.Controllers
{
    public class ProductMainGroupController : BaseController
    {
        ProductMainGroupRepository repo = new ProductMainGroupRepository();
        
        public ActionResult Index()
        {
            List<ProductMainGroupViewModel> model = repo.GetProductMainGroupList();
            TempData["ExportData"] = model;
            ViewBag.datasource = model;
            return View();
        }
        public ActionResult Create()
        {
            FillFropDowns();
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProductMainGroup model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Create(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Saved";
                    return RedirectToAction("Create");
                }
                else
                {
                    FillFropDowns();
                    return View(model);
                }
            }
            FillFropDowns();
            return View(model);
        }
        public ActionResult Edit(int? Id)
        {
            FillFropDowns();
            ProductMainGroup model = repo.GetProductMainGroup(Id ?? 0);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ProductMainGroup model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Edit(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Updated";
                    return RedirectToAction("Index");
                }
                else
                {
                    FillFropDowns();
                    return View(model);
                }
            }
            return View(model);
        }
        private void FillFropDowns()
        {
            FillProductType();
        }
        private void FillProductType()
        {
            DropDownRepository ddRepo = new DropDownRepository();
            DropDownListProperties DropdownProperties = new DropDownListProperties();
            DropdownProperties.DataSource = ddRepo.GetProductTypes();
            DropdownProperties.Width = "100%";
            DropDownListFields DropdownFields = new DropDownListFields();
            DropdownFields.Text = "prdTypeName";
            DropdownFields.Id = "prdTypeId";
            DropdownFields.Value = "prdTypeId";
            DropdownProperties.DropDownListFields = DropdownFields;
            ViewData["ProdTypeDropdownModel"] = DropdownProperties;
        }
    }
}

prms.web/Controllers/ProductSubGroupController.cs
using ems.core;
using ems.domain;
using ems.domain.ViewModels;
using Syncfusion.JavaScript.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prms.web.Controllers
{
    public class ProductSubGroupController : BaseController
    {
        ProductSubGroupRepository repo = new ProductSubGroupRepository();
        DropDownRepository ddrepo = new DropDownRepository();
        public ActionResult Index()
        {
            List<ProductSubGroupViewModel> model = repo.GetProductSubGroupList();
            TempData["ExportData"] = model;
            ViewBag.datasource = model;
            return View();
        }
        public ActionResult Create()
        {
            FillFropDowns();
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProductSubGroup model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Create(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Saved";
                    return RedirectToAction("Create");
                }
                else
                {
                    FillFropDowns();
                    return View(model);
                }
            }
            return View(model);
        }
        public ActionResult Edit(int? Id)
        {
            FillFropDowns();
            ProductSubGroup model = repo.GetProductSubGroup(Id ?? 0);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ProductSubGroup model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Edit(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Updated";
                    return RedirectToAction("Index");
                }
                else
                {
                    FillFropDowns();
                    return View(model);
                }
            }
            return View(model);
        }
        private void FillFropDowns()
        {
            FillProductGroup();
            FillGSTRates();
        }
        private void FillProductGroup()
        {
            DropDownListProperties DropdownProperties = new DropDownListProperties();
            DropdownProperties.DataSource = ddrepo.GetProductMainGroup();
            DropdownProperties.Width = "100%";
            DropDownListFields DropdownFields = new DropDownListFields();
            DropdownFields.Text = "prdMGName";
            DropdownFields.Id = "prdMGId";
            DropdownFields.Value = "prdMGId";
            DropdownProperties.DropDownListFields = DropdownFields;
            ViewData["ProdGroupDropdownModel"] = DropdownProperties;
        }
        private void FillGSTRates()
        {
            DropDownListProperties DropdownProperties = new DropDownListProperties();
            DropdownProperties.DataSource = ddrepo.GetGSTRate();
            DropdownProperties.Width = "100%";
            DropDownListFields DropdownFields = new DropDownListFields();
            DropdownFields.Text = "gstName";
            DropdownFields.Id = "gstId";
            DropdownFields.Value = "gstId";
            DropdownProperties.DropDownListFields = DropdownFields;
            ViewData["GSTRateDropdownModel"] = DropdownProperties;
        }
    }
}

prms.web/Controllers/ServiceExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ems.domain;
using ems.core;
using Syncfusion.EJ.Export;
using Syncfusion.JavaScript.Models;
using Syncfusion.XlsIO;
using ems.domain.ViewModels;

namespace prms.web.Controllers
{
    public class ServiceExpenseController : BaseController
    {
        ServiceExpenseRepository repo = new ServiceExpenseRepository();
        DropDownRepository ddrepo = new DropDownRepository();
        public ActionResult Index()
        {
            List<ServiceExpenseViewModel> model = repo.GetSeviceExpenseList();
            TempData["ExportData"] = model;
            ViewBag.datasource = model;
            return View();
        }
        public ActionResult Create()
        {
            ServiceExpense model = new ServiceExpense();
            FillDropDowns();
            return View(model);
        }
        public ActionResult Edit(int? Id)
        {
            FillDropDowns();
            ServiceExpense model = repo.GetServiceExpense(Id ?? 0);            
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(ServiceExpense model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Create(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Saved";
                    return RedirectToAction("Create");
                }
                else
                {
                    FillDropDowns();
                    return View(model);
                }
            }
            FillDropDowns();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ServiceExpense model)
        {
            if (ModelState.IsValid)
            {
                int rowsAffected = repo.Edit(model);
                if (rowsAffected > 0)
                {
                    TempData["message"] = "Successfully Updated";
                    return RedirectToAction("Index");
                }
                else
                {
                    FillDropDowns();
                    return View(model);
                }
            }
            return View(model);
        }
        public void FillDropDowns()
        {
            FillGSTRates();
            FillServiceExpenseType();
        }
        private void FillGSTRates()
        {
            DropDownListProperties DropdownProperties = new DropDownListProperties();
            DropdownProperties.DataSource = ddrepo.GetGSTRate();
            DropdownProperties.Width = "100%";
            DropDownListFields DropdownFields = new DropDownListFields();
            DropdownFields.Text = "gstName";
            DropdownFields.Id = "gstId";
            DropdownFields.Value = "gstId";
            DropdownProperties.DropDownListFields = DropdownFields;
            ViewData["GSTRateDropdownModel"] = DropdownProperties;
        }
        private void FillServiceExpenseType()
        {
            DropDownListProperties DropdownProperties = new DropDownListProperties();
            DropdownProperties.DataSource = new List<DropdownViewModel>()
            {
                new DropdownViewModel() {shortValue="SER", DisplayText = "Service"},
                new DropdownViewModel() {shortValue="EXP", DisplayText = "Expense" },
                new DropdownViewModel() {shortValue="BOTH", DisplayText="Both" }
            };
            DropdownProperties.Width = "100%";
            DropDownListFields DropdownFields = new DropDownListFields();
            DropdownFields.Text = "DisplayText";
            DropdownFields.Id = "shortValue";
            DropdownFields.Value = "shortValue";
            DropdownProperties.DropDownListFields = DropdownFields;
            ViewData["SerExpTypeDropdownModel"] = DropdownProperties;
        }
    }
}

prms.web/Controllers/ServiceInvoiceController.cs
using ems.core;
using ems.domain;
using ems.domain.ViewModels;
using Syncfusion.JavaScript.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prms.web.Controllers
{
    public class ServiceInvoiceController : BaseController
    {
        // GET: ServiceInvoice
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            ServiceIncome model = new ServiceIncome();
            model.HeadModel = new ems.domain.ServiceIncomeHD();
            model.ItemsModel = new List<ServiceIncomeDT>();
            for (int i = 0; i < 50; i++)
            {
                model.ItemsModel.Add(new ems.domain.ServiceIncomeDT() { slNo = i+1});
            }
            fillDropdowns();
            InitSyncDatePicker();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(ServiceIncome model)
        {
            if(ModelState.IsValid)
            {

            }
            return RedirectToAction("Create");
        }
        private void fillDropdowns()
        {
            fillCustomer();
            fillServiceDescription();
        }
        private void fillCustomer()
        {
            CustomerRepository _cusRepo = new CustomerRepository();
            List<Customer> cus = _cusRepo.GetCustomerList();

            DropDownListProperties DropdownProperties = new DropDownListProperties();
            DropdownProperties.DataSource = cus;
            DropdownProperties.Width = "100%";
            DropDownListFields DropdownFields = new DropDownListFields();
            DropdownFields.Text = "CusName";
            DropdownFields.Id = "CusId";
            DropdownFields.Value = "CusId";
            DropdownProperties.DropDownListFields = DropdownFields;
            ViewData["CustomerDropdownModel"] = DropdownProperties;
        }
        private void fillServiceDescription()
        {
            ServiceExpenseRepository _serRepo = new ServiceExpenseRepository();
            ViewData["ServiceDropdownModel"] = _serRepo.GetSeviceExpenseList();
        }
    }
}

prms.web/Views/Shared/_ControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">
    @* BEGIN Tabs *@
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    @* END Tabs *@
    <div class="tab-content">
        @* BEGIN Home Tab *@
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        @* END Home Tab *@
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        @* BEGIN Settings Tab *@
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
            </form>
        </div>
        @* END Settings Tab *@
    </div>
</aside>
@* Add the sidebar's background. This div must be placed immediately after the control sidebar *@
<div class="control-sidebar-bg"></div>

prms.web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using WebHelpers.Mvc5.Enum
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        @if (!string.IsNullOrWhiteSpace(ViewBag.Title))
        {
            @ViewBag.Title@:-
        }
        SKERP
    </title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @Styles.Render("~/Bundles/css")
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	 	@Styles.Render("~/Content/ej/web/Flat-Lime/ej.web.all.min.css")
      @Scripts.Render("~/Scripts/jquery-3.2.1.min.js")
	 	@Scripts.Render("~/Scripts/jsrender.min.js")
	 	@Scripts.Render("~/Scripts/ej/ej.web.all.min.js")
	 	@Scripts.Render("~/Scripts/ej/ej.unobtrusive.min.js")
</head>
<body class="hold-transition skin-green sidebar-mini">
    <div class="wrapper">
        @Html.Partial("_Header")
        @Html.Partial("_Sidebar")

        <div class="content-wrapper">
            @*<section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.Description</small>
                </h1>
            </section>*@

            <section class="content">
                @RenderBody()
                @Html.Partial("_MessageModal")
            </section>
        </div>

        @Html.Partial("_ControlSidebar")
    </div>

    <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
    <script src="@EnumHandler.HandlerUrl"></script>
    @Scripts.Render("~/Bundles/js")
    @Scripts.Render("~/Bundles/datatable")
    @Scripts.Render("~/bundles/jqueryval")    
    @RenderSection("ViewSpecificJavascript", required: false)
	@Html.EJ().ScriptManager()
</body>
</html>
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
@if (ViewBag.submitResult != null)
{
    <script type="text/javascript">
        $(window).on('load',function(){
            $('#modal-default').modal('show');
        });
    </script>
}

prms.web/Views/Shared/_MessageModal.cshtml
<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">PRMS</h4>
            </div>
            <div class="modal-body">
                <p>@ViewBag.submitResult</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

prms.web/Views/Shared/_Sidebar.cshtml
@using WebHelpers.Mvc5
<aside class="main-sidebar">
    <section class="sidebar">
        @* BEGIN Search *@
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        @* END Search *@
        @* BEGIN Menu *@
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">HEADER</li>
            <li class="@Url.IsLinkActive("Index", "Home")">
                <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> <span>Home</span></a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-cogs"></i> <span>General Masters</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@Url.IsLinkActive("Create","Customer")"><a href="@Url.Action("Create","Customer")"><i class="fa fa-dollar"></i> <span>Customer</span></a></li>
                    <li class="@Url.IsLinkActive("Create","Vendor")"><a href="@Url.Action("Create","Vendor")"><i class="fa fa-user-secret"></i> <span>Vendor</span></a></li>
                    <li class="@Url.IsLinkActive("Create","GST")"><a href="@Url.Action("Create","GST")"><i class="fa fa-ship"></i> <span>GST Rates</span></a></li>
                    <li class="@Url.IsLinkActive("Create","Warehouse")"><a href="@Url.Action("Create","Warehouse")"><i class="fa fa-ship"></i> <span>Warehouse</span></a></li>                    
                    <li class=""><a href="#"><i class="fa fa-ship"></i> <span>Fiscal Year</span></a></li>
                    <li class="@Url.IsLinkActive("Edit","Company")"><a href="@Url.Action("Edit","Company")"><i class="fa fa-ship"></i> <span>Company Details</span></a></li>                    
                    <li class="@Url.IsLinkActive("Create","Style")"><a href="@Url.Action("Create","Style")"><i class="fa fa-ship"></i> <span>Style Description</span></a></li>
                    <li class="@Url.IsLinkActive("Create","Fabric")"><a href="@Url.Action("Create","Fabric")"><i class="fa fa-ship"></i> <span>Fabric</span></a></li>
                    <li class="@Url.IsLinkActive("Create","Trim")"><a href="@Url.Action("Create","Trim")"><i class="fa fa-ship"></i> <span>Trims</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-industry"></i> <span>Purchase</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Purchase Indent</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Supplier Order</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>GRN</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Q.A</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Purchase Bill</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-industry"></i> <span>Sales</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Create","ProductMainGroup")"><i class="fa fa-tags"></i> <span>Product Main Group</span></a></li>
                    <li><a href="@Url.Action("Create","ProductSubGroup")"><i class="fa fa-tags"></i> <span>Product Sub Group</span></a></li>
                    <li><a href="#"><i class="fa fa-tags"></i> <span>Product Defenition</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Quotation</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>GIN</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Sales Invoice</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Stock Reconciliation</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-industry"></i> <span>Service</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Create","ServiceExpense")"><i class="fa fa-tags"></i> <span>Service/Expense Defenition</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Quotation</span></a></li>
                    <li><a href="@Url.Action("Create","ServiceInvoice")"><i class="fa fa-cube"></i> <span>Service Invoice</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Service Bill</span></a></li>                    
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-industry"></i> <span>Accounts</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-ship"></i> <span>Chart of Accounts</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Expense Bill</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Account Payables</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Account Receivables</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Payment to Vendors</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Receipt from Customer</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Bank/Cash Payment</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Bank/Cash Receipt</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Fund Transfer</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Debit Note</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Credit Note</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Journal Entry</span></a></li>
                    <li><a href="#"><i class="fa fa-cube"></i> <span>Bank Reconciliaton</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-hourglass-end"></i> <span>H.R</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-random"></i> <span>Department</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Designation</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Wage Grade</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Salary Period</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Employee</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Leaves</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Attendance Sheet</span></a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-hourglass-end"></i> <span>Reports</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-random"></i> <span>Stock Reports</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>GSTR-1</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>GSTR-2</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Purchase Reports</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Sales Reports</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Service Reports</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Trial Balance</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Balance Sheet</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Profit & Loss</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Trading  P&L</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Bank/Cash Status</span></a></li>
                    <li><a href="#"><i class="fa fa-random"></i> <span>Ledger Detailed Report</span></a></li>
                </ul>
            </li>
        </ul>
        @* END Menu *@
    </section>
</aside>